name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag timmymorr/favourite-svc:$(git rev-parse --short "$GITHUB_SHA")
    - name: Push the tagged Docker image
      run: docker push timmymorr/favourite-svc:$(git rev-parse --short "$GITHUB_SHA")
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag timmymorr/favourite-svc:latest
    - name: Push the latest Docker image
      run: docker push timmymorr/favourite-svc:latest
